-- =====================================================================
--  Impression 3D — schéma à coller dans le SQL Editor de Supabase
--  (MÊME projet que reservation-machines : ggmlfbxppgeivfvlxxrj)
--
--  Ce script AJOUTE deux tables (demandes, parametres).
--  Il NE touche PAS aux tables existantes etudiants / operateurs.
--  On peut le relancer sans risque (IF NOT EXISTS partout).
-- =====================================================================

-- ---------- Table des demandes d'impression --------------------------
create table if not exists public.demandes (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  etudiant_nom        text not null default '',
  etudiant_prenom     text not null default '',
  projet              text not null default '',
  fichier_nom         text not null default '',
  drive_file_id       text default '',
  drive_link          text default '',
  machine             text not null default 'bambulab',   -- bambulab | markforged
  volume_mm3          double precision default 0,
  bbox                text default '',                      -- "LxLxH mm"
  temps_estime_min    integer default 0,
  temps_final_min     integer default 0,
  statut              text not null default 'en_attente',  -- en_attente|validee|refusee|en_cours|imprimee
  encadrant_nom       text default '',
  encadrant_valide_at timestamptz,
  imprime_at          timestamptz,
  notes               text default '',                   -- commentaire de l'étudiant
  numero              integer default 0,                 -- n° incrémental par projet
  taraudage           boolean default false,
  insert_filete       boolean default false,
  usinage             boolean default false,
  finition            text default 'brouillon',          -- brouillon | finition
  temps_categorie     text default '',                   -- "moins de 3h" ...
  encadrant_commentaire text default ''
);

-- Colonnes ajoutées après coup (pour une base déjà créée : relançable sans risque)
alter table public.demandes add column if not exists numero               integer default 0;
alter table public.demandes add column if not exists taraudage            boolean default false;
alter table public.demandes add column if not exists insert_filete        boolean default false;
alter table public.demandes add column if not exists usinage              boolean default false;
alter table public.demandes add column if not exists finition             text default 'brouillon';
alter table public.demandes add column if not exists temps_categorie      text default '';
alter table public.demandes add column if not exists encadrant_commentaire text default '';
alter table public.demandes add column if not exists en_cours_at          timestamptz;
alter table public.demandes add column if not exists duree_reelle_min     integer default 0;
alter table public.demandes add column if not exists operateur_nom        text default '';

-- Index pour le suivi étudiant (recherche par nom/prénom) et les listes
create index if not exists demandes_statut_idx  on public.demandes (statut);
create index if not exists demandes_etudiant_idx on public.demandes (lower(etudiant_nom), lower(etudiant_prenom));
create index if not exists demandes_projet_idx   on public.demandes (projet);

-- ---------- Table des paramètres (clé / valeur) ----------------------
create table if not exists public.parametres (
  cle    text primary key,
  valeur text not null default ''
);

-- Valeurs par défaut (ne réécrase pas si déjà présentes)
insert into public.parametres (cle, valeur) values
  ('code_encadrant', '0000'),   -- code partagé de validation encadrant
  ('limite_defaut',  '10'),     -- limite d'impressions par projet (par défaut)
  ('limites_projets','{}'),     -- surcharges par projet (gérées par l'opérateur)
  -- Machines proposées (gérées en admin) : débit mm³/min, temps fixe min, taux de remplissage 0-1
  ('machines', '[{"nom":"Bambu Lab","emoji":"🟢","debit":300,"overhead":10,"taux":0.35,"desc":"FDM rapide — plastique"},{"nom":"Markforged","emoji":"🔵","debit":120,"overhead":15,"taux":0.35,"desc":"Composite renforcé"}]')
on conflict (cle) do nothing;

-- ---------- Sécurité (RLS) : accès anon, comme le reste de l'appli ---
alter table public.demandes   enable row level security;
alter table public.parametres enable row level security;

-- Demandes : lecture + insertion + mise à jour pour la clé anon
drop policy if exists demandes_all on public.demandes;
create policy demandes_all on public.demandes
  for all using (true) with check (true);

-- Paramètres : lecture + mise à jour (admin) pour la clé anon
drop policy if exists parametres_all on public.parametres;
create policy parametres_all on public.parametres
  for all using (true) with check (true);

-- ---------- Realtime (rafraîchissement discret des écrans opérateur/encadrant/suivi) ---------
-- Ajoute les tables à la publication realtime si pas déjà fait (etudiants et operateurs
-- servent au rafraîchissement silencieux des listes projet/étudiant/opérateur).
do $$
begin
  begin alter publication supabase_realtime add table public.demandes;   exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.parametres; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.etudiants; exception when duplicate_object then null; end;
end $$;
